// Receipt.tsx
import React from "react";
import logo from "../../../public/Logo Symbol.png"
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  Image,
} from "@react-pdf/renderer";

// ✅ Styles
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: "Helvetica",
    backgroundColor: "#F9FAFB",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottom: "2 solid #2C3E50",
    paddingBottom: 10,
    marginBottom: 20,
  },
  logo: {
    width: 80,
    height: 80,
  },
  companyInfo: {
    textAlign: "right",
  },
  title: {
    fontSize: 18,
    marginBottom: 20,
    color: "#2C3E50",
    textAlign: "center",
  },
  section: {
    marginBottom: 15,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  label: {
    fontWeight: "bold",
    color: "#374151",
  },
  value: {
    color: "#111827",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 10,
    color: "#6B7280",
  },
});

// ✅ Receipt Component
const Receipt = ({ receiptNo, name, amount, description, date }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Image style={styles.logo} src={logo} />
        <View style={styles.companyInfo}>
          <Text style={{ fontSize: 14, fontWeight: "bold" }}>
            International Journal of Sustainable Development Studies (IJSDS)
          </Text>
          <Text>Email: info@ijsds.org</Text>
          <Text>www.ijsds.org</Text>
        </View>
      </View>

      {/* Title */}
      <Text style={styles.title}>Payment Receipt</Text>

      {/* Payment Info */}
      <View style={styles.section}>
        <View style={styles.row}>
          <Text style={styles.label}>Receipt No:</Text>
          <Text style={styles.value}>{receiptNo}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Date:</Text>
          <Text style={styles.value}>{date}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Name:</Text>
          <Text style={styles.value}>{name}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Description:</Text>
          <Text style={styles.value}>{description}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Amount Paid:</Text>
          <Text style={styles.value}>₦{amount.toLocaleString()}</Text>
        </View>
      </View>

      {/* Footer */}
      <Text style={styles.footer}>
        This receipt was generated by IJSDS. Thank you for your payment.
      </Text>
    </Page>
  </Document>
);

export default Receipt;
