// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csihixcdxcldarcnclvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzaWhpeGNkeGNsZGFyY25jbHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzUxNTgsImV4cCI6MjA2ODg1MTE1OH0.5Pi00KHJXSGOCf0UqB35UOiyb_7XTJ8gO1wdIIfEXeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});